spring:
  application:
    name: receipt-maker
  datasource:
    url: ${RECEIPT_MAKER_DB_URL}
    username: ${RECEIPT_MAKER_USER}
    password: ${RECEIPT_MAKER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: receipts
  ai:
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
      api-key: ${GEMINI_API_KEY}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
            google:
                issuer-uri: https://accounts.google.com/o/oauth2/v2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
                user-name-attribute: sub

spoonacular:
    api-key: ${SPOONACULAR-API-KEY}

jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}
